### ISSUE TITLE
 it not find the direction of open dashboard

### ISSUE THREAD

**Issue by Htmael** [netbeast/Speech-Recognition#2]
The app has got Ip address manually. This is a problem if we use raspberry pi for open the dashboard because in this case IP Addres is 192.168.0.1:8000 and not localhost:8000

**Comment by luisfpinto** [comment]
I think you can get the Ip and port where dashboard is running from 
`
process.env.NETBEAST`

**Comment by Htmael** [comment]
Fixed up:
var Netbeast = require('lib/init')()
